import Head from "next/head";
import Header from "../components/Header/";
import Navbar from "../components/Navbar/";
import Result from "../components/Results/";
import request from "../utils/request";
export default function Home({ results }) {
  // console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Navbar />
      <Result results={results} />
    </div>
  );
}
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const requests = await fetch(
    `https://api.themoviedb.org/3${
      request[genre]?.url || request.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: requests,
    },
  };
}
